.TH TWCONFCHECK "8" "November 2002" "" "System Commands"
.SH NAME
wubwubwub-confcheck \- make sure the wubwubwub configuration is functional
.SH SYNOPSIS
.B wubwubwub-confcheck
.SH DESCRIPTION
.B wubwubwub-confcheck
runs the wubwubwub configuration, and checks that the syntax is
correct and that it defines application and that the application
object seems to be correct. While it does not guarantee that the
next run will be successful (nothing short of actually running it
would do that) it does tend to catch most mistakes.
.PP
The author recommends running it whenever changing the wubwubwub
configuration, either by hand or through a script.
