#!/usr/bin/python2.2

import os, sys
from twisted.python import usage

class Options(usage.Options):

    optParameters = [
                     ['port', 'p', 8384, 'The new port for Twisted Web to use'],
                     ['vhost', 'v', None, 'The virtual host name'],
                     ['apache-port', 'c', 80, 'Port apache is running on'],
                    ]

    optFlags = [
                ['apache', 'a', 'Add appropriate configuration to apache'],
                ['force', 'f', 'Overwrite existing configuration files']
               ]

    def opt_version(self):
        print "rptwisted: version 0.16"
	sys.exit()


header='''\
####
#### Automatically added by rptwisted
####
'''

file02vhostmonster='''\
from twisted.web import vhost
root.default.putChild('vhost', vhost.VHostMonsterResource())
'''

file50changeport='''\
for i in range(len(application.tcpPorts)):
    if application.tcpPorts[i][0] == 80:
        del application.tcpPorts[i]
        break

application.listenTCP(%(port)s, site)
'''

apacheConfig='''\
<VirtualHost *>
ProxyPass / http://localhost:%(port)s/vhost/http/%(vhost)s:%(apache-port)s/
ServerName %(vhost)s
ServerAdmin webmaster@%(vhost)s
</VirtualHost>
'''

def writeFile(name, content, force):
    if not force and os.path.exists(name):
         print "warning: %s exists, not touching" % name
         return
    fp = open(name+'-', 'w')
    fp.write(header)
    fp.write(content)
    fp.close()
    os.rename(name+'-', name)

def system(cmd):
    r = os.system(cmd)
    if r != 0:
        raise OSError("command returned non-zero: %d" % r)

def confdir(*names):
    return os.path.join('/etc/twisted-web', *names)

def a2confdir(*names):
    return os.path.join('/etc/apache2', *names)

def main():
    opt = Options()
    opt.parseOptions()
    force = opt['force']
    writeFile(confdir('local.d/02vhostmonster.py'), file02vhostmonster, force)
    writeFile(confdir('local.d/50changeport.py'), file50changeport % opt, force)
    if opt['apache']:
        fname = '%(vhost)s-%(apache-port)s' % opt
        if not os.path.exists(a2confdir('mods-enabled/proxy.load')):
            system('a2enmod proxy')
        writeFile(a2confdir('sites-available', fname), apacheConfig % opt,force)
	os.symlink('../sites-available/'+fname,
	           a2confdir('sites-enabled', fname))
        # ????
        # What should I write to
        # /var/lib/vhost-base/%(vhost)s/conf/apache2.conf ? Anything?
    open(confdir('disabled'), 'w').close()
    system('invoke-rc.d twisted-web restart')
    if opt['apache']:
        system('invoke-rc.d apache2 reload')

def run():
    try:
        main()
    except (IOError, OSError), e:
        sys.exit(str(e))
    except usage.UsageError, e:
        sys.exit(str(e))

if __name__ == '__main__':
    run()
