#!/usr/bin/python2.2

import os, sys
from twisted.python import usage

class Options(usage.Options):

    optParameters = [
                     ['port', 'p', 8384, 'The new port for Twisted Web to use'],
                     ['vhost', 'v', None, 'The virtual host name'],
                     ['apache-port', 'c', 80, 'Port apache is running on'],
                    ]

    optFlags = [
                ['apache', 'a', 'Add appropriate configuration to apache'],
                ['force', 'f', 'Overwrite existing configuration files']
               ]

    def opt_version(self):
        print "rptwisted: version 0.19"
	sys.exit()


header='''\
####
#### Automatically added by rptwisted
####
'''

file02vhostmonster='''\
from twisted.web import vhost
root.default.putChild('vhost', vhost.VHostMonsterResource())
'''

apacheConfig='''\
<VirtualHost *>
ProxyPass / http://localhost:%(port)s/vhost/http/%(vhost)s:%(apache_port)s/
ServerName %(vhost)s
ServerAdmin webmaster@%(vhost)s
</VirtualHost>
'''


def writeFile(name, content, force):
    if not force and os.path.exists(name):
         print "warning: %s exists, not modifying" % name
         return
    fp = open(name+'-', 'w')
    fp.write(header)
    fp.write(content)
    fp.close()
    os.rename(name+'-', name)


def system(cmd):
    r = os.system(cmd)
    if r != 0:
        raise OSError("command returned non-zero: %d" % r)


def confdir(*names):
    return os.path.join('/etc/twisted-web', *names)


def a2confdir(*names):
    return os.path.join('/etc/apache2', *names)


def setPorts(newPort)
    currentPorts = map(int, open('/etc/twisted-web/ports').read().split())
    if 80 in currentPorts:
        currentPorts.remove(80)
        open(confdir('disabled'), 'w').close()
    if newPort not in currentPorts:
        currentPorts.append(newPort)
    writeFile(confdir('ports'), '\n'.join(map(str, ports))+'\n', 1)


def addApacheVhost(vhost, apache_port, force):
    fname = '%(vhost)s-%(apache_port)s' % vars())
    if not os.path.exists(a2confdir('mods-enabled/proxy.load')):
        system('a2enmod proxy')
    writeFile(a2confdir('sites-available', fname), apacheConfig % vars(),force)
    os.symlink('../sites-available/'+fname,
               a2confdir('sites-enabled', fname))


def configureSystem(force, apache, port, vhost, apache_port)
    setPorts(port)
    writeFile(confdir('local.d/02vhostmonster.py'), file02vhostmonster, force)
    if apache:
        addApacheVhost(vhost, apache_port, force)
    for service in ['twisted-web']+apache*['apache2']:
        system('invoke-rc.d %s restart' % service)


def main(argv):
    opt = Options()
    opt.parseOptions(argv)
    configureSystem(opt['force'], opt['apache'], opt['port'], opt['vhost'],
                    opt['apache_port'])


def run():
    try:
        main(sys.argv[1:])
    except (IOError, OSError), e:
        sys.exit(str(e))
    except usage.UsageError, e:
        sys.exit(str(e))

if __name__ == '__main__':
    run()
