#!/bin/sh
set -e

#DEBHELPER#

. /usr/share/debconf/confmodule 

if [ -r /etc/wubwubwub/disable ]; then
	:
else
	if [ -n "`netstat -plunt | awk '{print $4}' | grep ':80$'`" ]; then
		echo "exit 0" > /etc/wubwubwub/disable
		db_input high wubwubwub/cant-bind || true 
		db_go || true
	else
		touch /etc/wubwubwub/disable 
	fi;
fi
update-rc.d wubwubwub defaults >/dev/null
invoke-rc.d wubwubwub start
db_stop
